grass-drops: [ ]
world-blacklist:
  - world_nether
  - world_the_end
chances:
  TREE: 22
  BUSH: 16
options:
  auto-update: false
  auto-generate-plants: true
  item-heads: true
########################################
#                                      #
#             BE Plugin             #
#                                      #
########################################

fixes:
  drop-skull: true
  scan-itemframe: true
  scan-chunk: true

settings:
  tpmessage-enable: true
  spawn-on-join: true

messages:
  tpmessage: "&a你已被传送至出生点"
  error-nospawnpoint: "&c无出生点设置"
  success-setspawn: "&a成功设置出生点"
  cmd-spawn-usage: "&c用法: /spawn"
  cmd-setspawn-usage: "&c用法: /setspawn"

spawn: { }

twerking:
  radius: 3
  chance: 0.1
watering-can:
  chance: 0.1
